<?php
/**
 * Created by PhpStorm.
 * User: rosl
 * Date: 12.12.16
 * Time: 2:21
 */

namespace app\controllers;

use app\models\ExchangeDirection;
use Yii;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;
use yii\web\Response;

class DirectionController extends ActiveController
{
 public $modelClass = 'app\models\ExchangeDirection';

 public function beforeAction($action)
 {
	 Yii::$app->response->format = Response::FORMAT_JSON;
	 return parent::beforeAction($action); // TODO: Change the autogenerated stub
 }
	public function actions(){
		$actions = parent::actions();
		unset($actions['index']);
		return $actions;
	}
	public function actionIndex(){
		$activeData = new ActiveDataProvider([
				'query' => ExchangeDirection::find(),
				'pagination' => false
		]);
		return $activeData;
	}
}